### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by gnimmelf** [jenkin/nodebb-plugin-embed-gmap#2]
Please add an example, and save your users (me!) a lot of fumbeling around. 

NodeBB is not too sharp on when it has properly set up a new plugin (1 or 2 restarts, a reload, and then a browser refresh?) so it is hard to tell if the plugin is laggin behind version, is buggy, or if I did not understand the always sparse documentation on NodeBB plugins....

Cheers.

**Comment by jenkin** [comment]
Eh, I'm not using nodebb anymore, sorry... :(

**Comment by gnimmelf** [comment]
No worries, if I can make it work, I will fork it. Hopefully I'm stuck with NodeBB for a while :-P
